ios workflow changes

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -121,14 +121,14 @@ workflows:
           flutter clean
 
           # Remove existing Pods and Podfile.lock to ensure a clean state
-          rm -rf Pods
-          rm -rf Podfile.lock
+#          rm -rf Pods
+#          rm -rf Podfile.lock
 
           # Check if Podfile exists before running pod install
-          if [ ! -f "Podfile" ]; then
-            echo "Error: No 'Podfile' found in the project directory."
-            exit 1
-          fi
+#          if [ ! -f "Podfile" ]; then
+#            echo "Error: No 'Podfile' found in the project directory."
+#            exit 1
+#          fi
 
           # Reinstall Flutter dependencies and iOS pods
           flutter pub get
